import { type Metadata } from "next";
import { type GeneralLayoutProps } from "@/types/app/layout-props/GeneralLayoutProps";

import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Fullstack Inventory Management App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<GeneralLayoutProps>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased font-sans`}
			>
				{children}
			</body>
		</html>
	);
}
